name: PR Check Workflow

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review, converted_to_draft]

jobs:
  check_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch the full history of commits
      - name: Fetch target branch (main) to compare with PR branch
        run: |
          git fetch origin main    
      - name: Run checks for the pull request
        run: |
          echo "Checking pull request..."
          # Add your custom check commands here
          # For example, you could check for file changes, run linters, etc.
      - name: Check for file changes in docs folder
        run: |
          # Ensure that both 'origin/main' and the PR branch are available for comparison
          git fetch origin main
          
          # List changed files between 'origin/main' and the current PR commit ($GITHUB_SHA)
          changed_files=$(git diff --name-only origin/main...$GITHUB_SHA)

          # Check if any of the changed files are in the 'docs/' folder
          if [[ "$changed_files" == *"docs/"* ]]; then
            echo "Documentation files were changed."
          else
            echo "No documentation files were changed."
          fi
